server:
  port: 8191
spring:
  alarm-log:
    warn:
      mail:
        enabled: true
        smtpHost: xxxxxxxxx
        smtpPort: xxx
        to: xxx
        from: xxxx
        username: xxx
        password: xxx
      warn-exception-extend: false
      simple-warn-info: false
      print-stack-trace: true
      max-retry-times: 1
      retry-sleep-millis: 3000
      do-warn-exception:
        - java.lang.Throwable
        - java.lang.Exception
debug: true
