server:
  port: 8191
spring:
  alarm-log:
    warn:
      mail:
        enabled: true
        smtpHost: smtp.163.com
        smtpPort: 465
        to: 2959698930@qq.com
        from: 15557422216@163.com
        username: 15557422216@163.com
        password: PSAVOVLHPJNOIYZY
        # xwxecsnkadlvebfd   kyhgzzftugjfecad  waar bkiw qhrc djbi
      warn-exception-extend: false
      simple-warn-info: false
      print-stack-trace: true
      max-retry-times: 1
      retry-sleep-millis: 3000
      do-warn-exception:
        - java.lang.Throwable
        - java.lang.Exception
debug: true
